apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.webapp.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          args: {{ toYaml .Values.webapp.args | nindent 10 }}
          ports:
            - containerPort: {{ .Values.webapp.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.webapp.resources.requests.cpu }}
            limits:
              cpu: {{ .Values.webapp.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.webapp.name }}
  ports:
    - port: {{ .Values.webapp.containerPort }}
      targetPort: {{ .Values.webapp.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.webapp.name }}
                port:
                  number: {{ .Values.webapp.containerPort }}